---
name: Request a Feature
about: "..."
title: ''
labels: ''
assignees: ''

---

body:
- type: checkboxes
  id: Balancing
  attributes:
    label: Does this need to be balanced?
    description: Check if it needs to be balanced. Things like renames do not need to be balanced. Damage increases do.
    options:
      - label: Requires balancing?
  
